name: Test
on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Get dependencies
        run: |
          go mod download
          go mod verify
      - name: Test
        run: go test -v ./deploykeychain
