name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Get dependencies
        run: |
          go mod download
          go mod verify
      - name: Test
        run: go test -v ./deploykeychain
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_PAT: ${{ secrets.HOMEBREW_PAT }}
      - name: Push to Gemfury
        env:
          GEMFURY_TOKEN: ${{ secrets.GEMFURY_TOKEN }}
        run: |
          curl -F package=@dist/*_linux_386.deb https://{$GEMFURY_TOKEN}@push.fury.io/nint8835
          curl -F package=@dist/*_linux_amd64.deb https://{$GEMFURY_TOKEN}@push.fury.io/nint8835
          curl -F package=@dist/*_linux_arm64.deb https://{$GEMFURY_TOKEN}@push.fury.io/nint8835
          curl -F package=@dist/*_linux_386.rpm https://{$GEMFURY_TOKEN}@push.fury.io/nint8835
          curl -F package=@dist/*_linux_amd64.rpm https://{$GEMFURY_TOKEN}@push.fury.io/nint8835
          curl -F package=@dist/*_linux_arm64.rpm https://{$GEMFURY_TOKEN}@push.fury.io/nint8835
